//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_A6.AccountManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataModel", Namespace="http://schemas.datacontract.org/2004/07/A4")]
    [System.SerializableAttribute()]
    public partial class DataModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp_A6.AccountManager.Operation[] operationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int servicesUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idx {
            get {
                return this.idxField;
            }
            set {
                if ((this.idxField.Equals(value) != true)) {
                    this.idxField = value;
                    this.RaisePropertyChanged("idx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp_A6.AccountManager.Operation[] operations {
            get {
                return this.operationsField;
            }
            set {
                if ((object.ReferenceEquals(this.operationsField, value) != true)) {
                    this.operationsField = value;
                    this.RaisePropertyChanged("operations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int servicesUsed {
            get {
                return this.servicesUsedField;
            }
            set {
                if ((this.servicesUsedField.Equals(value) != true)) {
                    this.servicesUsedField = value;
                    this.RaisePropertyChanged("servicesUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/A4")]
    [System.SerializableAttribute()]
    public partial class Operation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opName {
            get {
                return this.opNameField;
            }
            set {
                if ((object.ReferenceEquals(this.opNameField, value) != true)) {
                    this.opNameField = value;
                    this.RaisePropertyChanged("opName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opResult {
            get {
                return this.opResultField;
            }
            set {
                if ((object.ReferenceEquals(this.opResultField, value) != true)) {
                    this.opResultField = value;
                    this.RaisePropertyChanged("opResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountManager.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindProfile", ReplyAction="http://tempuri.org/IService1/FindProfileResponse")]
        WebApp_A6.AccountManager.DataModel FindProfile(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindProfile", ReplyAction="http://tempuri.org/IService1/FindProfileResponse")]
        System.Threading.Tasks.Task<WebApp_A6.AccountManager.DataModel> FindProfileAsync(string uName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Encrypt", ReplyAction="http://tempuri.org/IService1/EncryptResponse")]
        string Encrypt(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Encrypt", ReplyAction="http://tempuri.org/IService1/EncryptResponse")]
        System.Threading.Tasks.Task<string> EncryptAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        string Decrypt(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        System.Threading.Tasks.Task<string> DecryptAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostFile", ReplyAction="http://tempuri.org/IService1/PostFileResponse")]
        string PostFile(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostFile", ReplyAction="http://tempuri.org/IService1/PostFileResponse")]
        System.Threading.Tasks.Task<string> PostFileAsync(string filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApp_A6.AccountManager.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApp_A6.AccountManager.IService1>, WebApp_A6.AccountManager.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp_A6.AccountManager.DataModel FindProfile(string uName) {
            return base.Channel.FindProfile(uName);
        }
        
        public System.Threading.Tasks.Task<WebApp_A6.AccountManager.DataModel> FindProfileAsync(string uName) {
            return base.Channel.FindProfileAsync(uName);
        }
        
        public string Encrypt(string filename) {
            return base.Channel.Encrypt(filename);
        }
        
        public System.Threading.Tasks.Task<string> EncryptAsync(string filename) {
            return base.Channel.EncryptAsync(filename);
        }
        
        public string Decrypt(string filename) {
            return base.Channel.Decrypt(filename);
        }
        
        public System.Threading.Tasks.Task<string> DecryptAsync(string filename) {
            return base.Channel.DecryptAsync(filename);
        }
        
        public string PostFile(string filename) {
            return base.Channel.PostFile(filename);
        }
        
        public System.Threading.Tasks.Task<string> PostFileAsync(string filename) {
            return base.Channel.PostFileAsync(filename);
        }
    }
}
